import * as fs from 'fs';
import * as path from 'path';
import type { OpenLookReport, OpenLookSpec } from './types.js';
import { getProjectInfo } from './project.js';

export async function generateReport(
  spec: OpenLookSpec,
  report: OpenLookReport,
  videoPath?: string
): Promise<string> {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
  const projectInfo = await getProjectInfo();
  const reportDir = path.join(projectInfo.root, 'reports', `${spec.id}-${timestamp}`);

  fs.mkdirSync(reportDir, { recursive: true });
  fs.writeFileSync(
    path.join(reportDir, 'report.json'),
    JSON.stringify(report, null, 2),
    'utf-8'
  );
  fs.writeFileSync(
    path.join(reportDir, 'report.md'),
    generateMarkdownReport(spec, report),
    'utf-8'
  );

  if (videoPath && fs.existsSync(videoPath)) {
    const ext = path.extname(videoPath) || '.webm';
    const dest = path.join(reportDir, `recording${ext}`);
    fs.copyFileSync(videoPath, dest);
  }

  return reportDir;
}

function generateMarkdownReport(spec: OpenLookSpec, report: OpenLookReport): string {
  const lines: string[] = [];

  lines.push('# OpenLook Report');
  lines.push('');
  lines.push(`**Verdict:** ${report.verdict.toUpperCase()}`);
  lines.push(`**Spec:** ${spec.id}`);
  lines.push(`**URL:** ${spec.url}`);
  lines.push(`**Viewport:** ${spec.viewport.width}x${spec.viewport.height}`);
  lines.push(`**Generated:** ${report.timestamp}`);
  lines.push('');
  lines.push(report.summary);
  lines.push('');

  lines.push('## Checks');
  lines.push('');
  lines.push(`Passed ${report.checks_passed}/${report.checks_total}`);
  lines.push('');

  for (const [index, result] of report.results.entries()) {
    lines.push(`### ${index + 1}. ${result.passed ? '✅' : '❌'} ${result.check.id}`);
    lines.push('');
    lines.push(`**Question:** ${result.check.question}`);
    lines.push('');
    lines.push(`**Pass:** ${result.check.pass}`);
    lines.push('');
    lines.push(`**Fail:** ${result.check.fail}`);
    lines.push('');
    lines.push(`**Reasoning:** ${result.reasoning}`);
    lines.push('');

    if (result.fix) {
      lines.push(`**Fix:** ${result.fix}`);
      lines.push('');
    }

    if (result.recommendations?.length) {
      lines.push('**Recommendations:**');
      result.recommendations.forEach((rec) => lines.push(`- ${rec}`));
      lines.push('');
    }
  }

  if (report.recommendations?.length) {
    lines.push('## Overall Recommendations');
    lines.push('');
    report.recommendations.forEach((rec) => lines.push(`- ${rec}`));
    lines.push('');
  }

  lines.push('---');
  lines.push('Generated by OpenLook.');

  return lines.join('\n');
}
